-- migration: create table empresas
CREATE TABLE IF NOT EXISTS empresas (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  ruc VARCHAR(50) NOT NULL UNIQUE,
  direccion TEXT,
  rubro VARCHAR(255),
  esactivo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

ALTER TABLE empresas ADD COLUMN IF NOT EXISTS ruc VARCHAR(50) NOT NULL UNIQUE;
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS rubro VARCHAR(255);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS esactivo BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now();
